M48
; DRILL file {KiCad (6.0.10-0)} date Friday, February 24, 2023 at 10:42:19 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-24T22:42:19-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X4.2Y-2.3
X4.3Y-3.3
X4.4Y-2.7
X4.6Y-2.8
X4.7Y-2.1
X4.7Y-3.1
X5.1Y-3.0
X5.4Y-2.7
T2
X4.9Y-2.3
X5.1Y-2.3
T0
M30
